#!/usr/bin/perl -w
use v5.028;
use utf8;

my $debug = $ENV{DEBUG} // 1;
my $number = int(1 + rand 100);

say "Guess a number between 1 and 100";
say "The secret number is $number" if $debug;

while (1) {
	chomp (my $guess = <STDIN>);
	if ($guess =~ /quit|exit|^\s*$/i) {
		last;
	} elsif ($guess < $number) {
		say "Too low";
	} elsif ($guess > $number) {
		say "Too high";
	} elsif ($guess == $number) {
		say "Congratz! You guessed it right.";
		last;
	}
}
