#!/usr/bin/perl -w
use v5.026;

@ARGV = glob "*" unless @ARGV;
my $oldest_name = shift @ARGV;
my $oldest_age = -M $oldest_name;

for (@ARGV) {
	my $age = -M || 0;
	($oldest_name, $oldest_age) = ($_, $age) if $age > $oldest_age;
}
printf ("The oldest file is %s with an age of %.1f days\n", $oldest_name, $oldest_age);
