#!/usr/bin/perl
use v5.028;
use warnings;
use utf8;

while(<>) {
	chomp;
	if (m{(?<word>\w*a\b)}) {
		say "Matched: |$`<$&>$'|";
		say "\$+{word} contains '$+{word}'";
	} else {
		say "No match: |$_|";
	}
}
